version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailor-website
    ports:
      - "8080:8080"
    environment:
      # Tu tylko wskazujemy nazwę zmiennej, jej wartość podasz w Portainerze
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: baza_i_stremio_default